CONF_OPTIONS_INTERVAL_OF_UPDATE_OF_ANALOG_INPUTS = "interval_of_update_of_analog_inputs"
CONF_OPTIONS_INTERVAL_OF_UPDATE_OF_COUNTERS = "interval_of_update_of_counters"
CONF_OPTIONS_INTERVAL_OF_UPDATE_OF_DIGITAL_INPUTS = "interval_of_update_of_digital_inputs"
CONF_OPTIONS_INTERVAL_OF_UPDATE_OF_RELAYS = "interval_of_update_of_relays"

DOMAIN = "ipx800v3"

NUMBER_OF_ANALOG_INPUTS = 16
NUMBER_OF_DIGITAL_INPUTS = 32
NUMBER_OF_RELAYS = 32
NUMBER_OF_COUNTERS = 8
